Repository varunherlekar/lets-do-it, pull requests merged in 2021-10, with the labels that each got.

#3 Fix: UI Issue #2 & some more fixes for better UI/UX
  index.html
  style.css
Labels: hacktoberfest-accepted

#5 error message added for empty task
  app.js
Labels: hacktoberfest-accepted

#8 Completed task list
  app.js
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#14 Fix: Edit Task
  app.js
Labels: hacktoberfest-accepted

#19 Style: UI Header fix and color pallet enhancement
  Screenshot-main-app.png
  index.html
  style.css
Labels: hacktoberfest-accepted

#26 Fixed issue - Feature to restore the completed task
  app.js
Labels: enhancement, hacktoberfest-accepted

#35 Removed quotes api and background image
  index.html
  quotes.js
  style.css
Labels: hacktoberfest-accepted

#39 ADDED: Option to remove items once it has been marked completed.
  app.js
Labels: hacktoberfest-accepted

#38 Added missing main tag and fixed footer position
  index.html
  style.css
Labels: hacktoberfest-accepted

#43 strike-through added for completed tasks
  app.js
Labels: hacktoberfest-accepted

#48 ADDED: Single Function for OnClick Buttons for Completed Tasks
  app.js
Labels: hacktoberfest-accepted, hacktoberfest
